In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv(r"C:\Users\aryan\OneDrive\Desktop\World Cup Predictor\results_clean.csv")
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,tournament_weight,result
0,1990-01-12,Algeria,Mali,5,0,Friendly,Paris,France,True,0.5,H
1,1990-01-14,Algeria,Cameroon,3,1,Friendly,Paris,France,True,0.5,H
2,1990-01-17,Greece,Belgium,2,0,Friendly,Athens,Greece,False,0.5,H
3,1990-01-17,Mexico,Argentina,2,0,Friendly,Los Angeles,United States,True,0.5,H
4,1990-01-20,Malawi,Tanzania,2,2,Friendly,Lobamba,Swaziland,True,0.5,D

In [11]:
# Starting rating for every team
STARTING_ELO = 1500

# K-factor — controls how much ratings change after each match
# We multiply by tournament_weight so WC matches matter more
BASE_K = 30

# Home advantage — home team gets a bonus
HOME_ADVANTAGE = 100

# Dictionary to store every team's current rating
elo_ratings = {}

def get_elo(team):
    if team not in elo_ratings:
        elo_ratings[team] = STARTING_ELO
    return elo_ratings[team]

print("Elo system ready!")

Elo system ready!

In [12]:
def expected_score(rating_a, rating_b):
    return 1 / (1 + 10 ** ((rating_b - rating_a) / 400))

def update_elo(home_team, away_team, home_score, away_score, tournament_weight, neutral):
    # Get current ratings
    home_elo = get_elo(home_team)
    away_elo = get_elo(away_team)
    
    # Add home advantage if not a neutral venue
    if neutral:
        home_elo_adjusted = home_elo
    else:
        home_elo_adjusted = home_elo + HOME_ADVANTAGE
    
    # Expected scores
    home_expected = expected_score(home_elo_adjusted, away_elo)
    away_expected = expected_score(away_elo, home_elo_adjusted)
    
    # Actual scores
    if home_score > away_score:
        home_actual, away_actual = 1, 0
    elif home_score < away_score:
        home_actual, away_actual = 0, 1
    else:
        home_actual, away_actual = 0.5, 0.5
    
    # K factor adjusted by tournament weight
    k = BASE_K * tournament_weight
    
    # Update ratings
    elo_ratings[home_team] = home_elo + k * (home_actual - home_expected)
    elo_ratings[away_team] = away_elo + k * (away_actual - away_expected)

print("Functions ready!")

Functions ready!

In [13]:
# Sort by date so we process matches in order
df = df.sort_values('date').reset_index(drop=True)

# Loop through every match and update ratings
for _, row in df.iterrows():
    update_elo(
        home_team=row['home_team'],
        away_team=row['away_team'],
        home_score=row['home_score'],
        away_score=row['away_score'],
        tournament_weight=row['tournament_weight'],
        neutral=row['neutral']
    )

print(f"Processed {len(df)} matches!")
print(f"Total teams rated: {len(elo_ratings)}")

Processed 32101 matches!
Total teams rated: 323

In [7]:
elo_df = pd.DataFrame(list(elo_ratings.items()), columns=['team', 'elo'])
elo_df = elo_df.sort_values('elo', ascending=False).reset_index(drop=True)
elo_df.head(20)

           team          elo
0         Spain  2188.176132
1     Argentina  2100.244381
2        France  2074.344160
3       England  2035.785502
4       Ecuador  2024.587277
5        Turkey  2015.297093
6        Brazil  1970.323402
7      Portugal  1970.044524
8        Norway  1968.683891
9      Colombia  1968.493194
10      Morocco  1966.921886
11        Japan  1953.515629
12  Netherlands  1949.522664
13     Paraguay  1946.579116
14      Germany  1943.236716
15       Mexico  1937.412549
16      Croatia  1937.407617
17      Senegal  1931.689386
18      Uruguay  1922.472768
19  Switzerland  1920.362211

In [8]:
STARTING_ELO = 1500
BASE_K = 30
HOME_ADVANTAGE = 100
DECAY = 0.99  # ratings drift 1% back toward 1500 each match

elo_ratings = {}

def get_elo(team):
    if team not in elo_ratings:
        elo_ratings[team] = STARTING_ELO
    return elo_ratings[team]

def expected_score(rating_a, rating_b):
    return 1 / (1 + 10 ** ((rating_b - rating_a) / 400))

def update_elo(home_team, away_team, home_score, away_score, tournament_weight, neutral):
    home_elo = get_elo(home_team)
    away_elo = get_elo(away_team)

    # Apply decay — ratings drift toward 1500 over time
    elo_ratings[home_team] = STARTING_ELO + (home_elo - STARTING_ELO) * DECAY
    elo_ratings[away_team] = STARTING_ELO + (away_elo - STARTING_ELO) * DECAY

    home_elo = elo_ratings[home_team]
    away_elo = elo_ratings[away_team]

    if neutral:
        home_elo_adjusted = home_elo
    else:
        home_elo_adjusted = home_elo + HOME_ADVANTAGE

    home_expected = expected_score(home_elo_adjusted, away_elo)
    away_expected = expected_score(away_elo, home_elo_adjusted)

    if home_score > away_score:
        home_actual, away_actual = 1, 0
    elif home_score < away_score:
        home_actual, away_actual = 0, 1
    else:
        home_actual, away_actual = 0.5, 0.5

    k = BASE_K * tournament_weight

    elo_ratings[home_team] = elo_ratings[home_team] + k * (home_actual - home_expected)
    elo_ratings[away_team] = elo_ratings[away_team] + k * (away_actual - away_expected)

# Reprocess all matches
for _, row in df.iterrows():
    update_elo(
        home_team=row['home_team'],
        away_team=row['away_team'],
        home_score=row['home_score'],
        away_score=row['away_score'],
        tournament_weight=row['tournament_weight'],
        neutral=row['neutral']
    )

# View top 20
elo_df = pd.DataFrame(list(elo_ratings.items()), columns=['team', 'elo'])
elo_df = elo_df.sort_values('elo', ascending=False).reset_index(drop=True)
elo_df.index += 1
elo_df.head(20)

           team          elo
1         Spain  1917.311952
2        France  1828.266029
3       Morocco  1827.315061
4        Turkey  1823.420350
5     Argentina  1817.413882
6       England  1817.402483
7       Senegal  1810.813940
8       Nigeria  1804.828657
9        Norway  1785.151106
10        Japan  1784.196888
11      Ecuador  1777.562616
12    Australia  1761.945001
13      Algeria  1753.629798
14      Germany  1744.686677
15     Portugal  1744.644085
16  Netherlands  1734.493439
17      Croatia  1732.246193
18  Switzerland  1731.769921
19       Mexico  1731.026772
20        Egypt  1730.071164

In [16]:
STARTING_ELO = 1500
HOME_ADVANTAGE = 100

elo_ratings = {}

def get_elo(team):
    if team not in elo_ratings:
        elo_ratings[team] = STARTING_ELO
    return elo_ratings[team]

def expected_score(rating_a, rating_b):
    return 1 / (1 + 10 ** ((rating_b - rating_a) / 400))

def update_elo(home_team, away_team, home_score, away_score, tournament_weight, neutral, date):
    home_elo = get_elo(home_team)
    away_elo = get_elo(away_team)

    if neutral:
        home_elo_adjusted = home_elo
    else:
        home_elo_adjusted = home_elo + HOME_ADVANTAGE

    home_expected = expected_score(home_elo_adjusted, away_elo)
    away_expected = expected_score(away_elo, home_elo_adjusted)

    if home_score > away_score:
        home_actual, away_actual = 1, 0
    elif home_score < away_score:
        home_actual, away_actual = 0, 1
    else:
        home_actual, away_actual = 0.5, 0.5

    year = pd.to_datetime(date).year
    if year >= 2022:
        base_k = 35
    elif year >= 2018:
        base_k = 30
    else:
        base_k = 20

    k = base_k * tournament_weight

    elo_ratings[home_team] = home_elo + k * (home_actual - home_expected)
    elo_ratings[away_team] = away_elo + k * (away_actual - away_expected)

for _, row in df.iterrows():
    update_elo(
        home_team=row['home_team'],
        away_team=row['away_team'],
        home_score=row['home_score'],
        away_score=row['away_score'],
        tournament_weight=row['tournament_weight'],
        neutral=row['neutral'],
        date=row['date']
    )

elo_df = pd.DataFrame(list(elo_ratings.items()), columns=['team', 'elo'])
elo_df = elo_df.sort_values('elo', ascending=False).reset_index(drop=True)
elo_df.index += 1
elo_df.head(20)

           team          elo
1         Spain  2169.690841
2     Argentina  2047.584193
3       England  2033.353422
4        France  2020.625388
5       Ecuador  1996.118091
6        Turkey  1993.245154
7        Norway  1956.731310
8       Morocco  1949.295775
9      Colombia  1926.877556
10      Senegal  1925.739655
11     Paraguay  1923.215588
12       Brazil  1920.898615
13        Japan  1919.998333
14    Australia  1913.551525
15      Nigeria  1912.790764
16       Mexico  1911.874693
17     Portugal  1908.832929
18  Netherlands  1895.359242
19      Croatia  1884.979037
20      Germany  1883.699925

In [17]:
teams_to_check = ['Germany', 'Portugal', 'Netherlands', 'Italy', 
                   'Belgium', 'Croatia', 'Uruguay', 'USA', 
                   'Ecuador', 'Turkey', 'Norway', 'Paraguay']

check = elo_df[elo_df['team'].isin(teams_to_check)]
print(check.to_string())

           team          elo
5       Ecuador  1996.118091
6        Turkey  1993.245154
7        Norway  1956.731310
11     Paraguay  1923.215588
17     Portugal  1908.832929
18  Netherlands  1895.359242
19      Croatia  1884.979037
20      Germany  1883.699925
22      Uruguay  1875.887717
33        Italy  1810.958705
36      Belgium  1780.811104

In [18]:
gs = pd.read_csv(r"C:\Users\aryan\OneDrive\Desktop\World Cup Predictor\group_stages_clean.csv")
wc_teams = gs['nation'].unique()

wc_elo = elo_df[elo_df['team'].isin(wc_teams)].reset_index(drop=True)
wc_elo.index += 1
print(f"Total WC teams: {len(wc_elo)}")
wc_elo

Total WC teams: 48

                      team          elo
1                    Spain  2169.690841
2                Argentina  2047.584193
3                  England  2033.353422
4                   France  2020.625388
5                  Ecuador  1996.118091
6                   Turkey  1993.245154
7                   Norway  1956.731310
8                  Morocco  1949.295775
9                 Colombia  1926.877556
10                 Senegal  1925.739655
11                Paraguay  1923.215588
12                  Brazil  1920.898615
13                   Japan  1919.998333
14               Australia  1913.551525
15                  Mexico  1911.874693
16                Portugal  1908.832929
17             Netherlands  1895.359242
18                 Croatia  1884.979037
19                 Germany  1883.699925
20             Switzerland  1877.156919
21                 Uruguay  1875.887717
22                  Canada  1854.258069
23             South Korea  1852.684552
24                  Panama  1851.550605
25              Uzbekistan  1847.242154
26                 Algeria  1837.945150
27                    Iran  1834.756287
28                   Egypt  1825.410140
29                DR Congo  1817.059512
30                    Iraq  1815.112054
31                Scotland  1798.724277
32                 Belgium  1780.811104
33                  Jordan  1776.149458
34             Ivory Coast  1772.074449
35                   Haiti  1771.228278
36                 Austria  1744.681088
37           United States  1741.311542
38             New Zealand  1741.154414
39                  Sweden  1701.549376
40                 Tunisia  1699.240512
41              Cape Verde  1698.064300
42            Saudi Arabia  1693.682605
43                 Curaçao  1674.498352
44          Czech Republic  1670.132295
45  Bosnia and Herzegovina  1641.615403
46                   Ghana  1641.552810
47                   Qatar  1622.736690
48            South Africa  1606.265464

In [19]:
print(gs[gs['nation'] == 'Norway'])

   group  position  nation
35     I         4  Norway

In [20]:
wc_elo.to_csv(r"C:\Users\aryan\OneDrive\Desktop\World Cup Predictor\elo_ratings.csv", index=False)
print("Saved!")

Saved!

In [21]:
# Save ALL teams, not just WC teams
full_elo = pd.DataFrame(list(elo_ratings.items()), columns=['team', 'elo'])
full_elo = full_elo.sort_values('elo', ascending=False).reset_index(drop=True)
full_elo.to_csv(r"C:\Users\aryan\OneDrive\Desktop\World Cup Predictor\elo_all_teams.csv", index=False)
print(f"Saved {len(full_elo)} teams!")

Saved 323 teams!